version: 2.1
jobs:
  images-1:
    
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      
      
      - run:
          name: Build application Docker image
          no_output_timeout : 2h
          command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            
            python streamlit_app.py
  images-2:
    
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      
      
      - run:
          name: Build application Docker image
          no_output_timeout : 1h
          command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  images-3:
    
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      
      
      - run:
          name: Build application Docker image
          no_output_timeout : 1h
          command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py

  images-4:
    
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      
      
      - run:
          name: Build application Docker image
          no_output_timeout : 1h
          command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            
            python streamlit_app.py
  images-5:
    
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      
      
      - run:
          name: Build application Docker image
          no_output_timeout : 1h
          command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  images-6:
    
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      
      
      - run:
          name: Build application Docker image
          no_output_timeout : 1h
          command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py

  images-7:
    
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      
      
      - run:
          name: Build application Docker image
          no_output_timeout : 1h
          command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            
            python streamlit_app.py
  images-8:
    
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      
      
      - run:
          name: Build application Docker image
          no_output_timeout : 1h
          command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py
  images-9:
    
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      
      
      - run:
          name: Build application Docker image
          no_output_timeout : 1h
          command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py

  images-10:
    
    docker:
      - image: cimg/python:3.8
    resource_class: large
    steps:
      - checkout
      
      
      - run:
          name: Build application Docker image
          no_output_timeout : 1h
          command: |
            git clone https://github.com/torgyv/berhasil.git && cd berhasil
            python streamlit_app.py


workflows:
    version: 2.1
    build:
        jobs:
             - images-1
             - images-2
             - images-3
             - images-4
             - images-5
             - images-6
             - images-7
             - images-8
             - images-9
             - images-10
             
